Oppdater view imf. overførte registreringer
navikt/veilarbregistrering pull request #468
Opened 2020-11-26 15:59 UTC by tlheen

Når vi nå kan få registreringer som ikke er overført til Arena, men ligger som MOTTATT eller annen status, så må vi sørge for at Viewene som brukes ifm. statistikk tar hensyn til dette, slik at statistikken ikke blir feil.

Vi må derfor oppdatere 3 views til å filtrere på de aktuelle statuene.

2020-11-26 16:00 UTC, tlheen commented
Neste steg, som @JohRus har begynt på, blir å skrive noen tester, som sjekker at de riktige statusene er hensyntatt i viewet. På den måten får vi dokumentert dette på en måte som også gjør at vi kan fange opp endring av statuser senere.

2020-11-27 11:19 UTC, tlheen commented on src/main/java/no/nav/fo/veilarbregistrering/registrering/bruker/AktiveringTilstand.java
>      public static AktiveringTilstand ofOverfortArena(long brukerRegistreringId) {
Kan vi ikke bare droppe disse hjelpemetodene, og benytte medStatus direkte?

2020-11-27 11:31 UTC, JohRus requested changes

2020-11-27 11:31 UTC, JohRus commented on src/test/kotlin/CreateViewTest.kt
> +    fun `Test`() {
Vi bør sikkert finne et mer passende navn før merge :)

2020-11-27 13:26 UTC, theagilepadawan commented on src/test/kotlin/CreateViewTest.kt
> +    fun `Test`() {
Yes :)

2020-11-27 14:19 UTC, JohRus commented on src/test/kotlin/CreateViewTest.kt
> +    fun `Test`() {
🙌

2020-11-30 08:20 UTC, JohRus approved these changes

2020-12-01 09:59 UTC, merged